---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: prometheus-grafana
  creationTimestamp: "2022-10-27T06:05:38Z"
  labels:
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.2.1
    helm.sh/chart: grafana-6.43.0
  name: stable-grafana-svc-lb
  namespace: prometheus-grafana
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http-web
    port: 8888
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: stable
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
